backend:
  name: git-gateway
  branch: master  # o la rama principal de tu repo

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "proyectos"
    label: "Proyectos"
    folder: "src/content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen destacada", name: "thumbnail", widget: "image" }
      - { label: "Galería de imágenes", name: "gallery", widget: "list", field: { label: "Imagen", name: "image", widget: "image" } }
      - { label: "Etiquetas", name: "tags", widget: "list", default: [], hint: "Agrega palabras clave como etiquetas (ej: diseño, web, UX)" }
      - { label: "Contenido", name: "body", widget: "markdown" }