backend:
  name: git-gateway
  branch: master  # o la rama principal de tu repo

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "proyectos"
    label: "Proyectos"
    folder: "src/content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen destacada", name: "thumbnail", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
